print('enter your name')
name=input()
print('enter your age')
age=int(input())
print('enter your school name')
school=input()
print('enter your country name')
country=input()
print('hi {} of age {},i really like the school {}, and what a country {} is.'.format(name,age,school,country))