s='My name is Adrik'
print(s.isalpha())
print(s.isalnum())
print(s.islower())
print(s.isupper())
print(s.count('a'))
print(s.find('Adrik'))
print(s.capitalize())
print(s.casefold())
print(s.center(100,'*'))
print(s.isspace())
print(s.join('-'))
print(s.title())
print(s.istitle())
print(s.isspace())
print(s.lstrip())
print(s.replace('a','d'))
print(s.split())
print(s.swapcase())
print(s.lower())
print(s.upper())

