name=input('enter your name')
maths=float(input('enter your maths marks:'))
science=float(input('enter your science marks:'))
english=float(input('enter your english marks:'))
total=int(input('enter your total marks'))
print('\n')
print(' '*10,'Report Card',' '*10)
print('\nstudent name:',name)
print(30*'-')
print('maths marks:',maths)
print('science marks:',science)
print('english marks:',english)
print(30*'-')
tot=int(maths+science+english)
print(tot,',this is the total marks you gained out of total,',total)
per=int((tot/total)*100)
print(per,',this is the percentage of your marks.')